version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fruits_vegetables_app
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - ./:/var/www/html
      - ./var/log:/var/www/html/var/log
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
    networks:
      - fruits_vegetables_network

networks:
  fruits_vegetables_network:
    driver: bridge